---
version: '3.4'
services:
  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8000'
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.19.6
    network_mode: host
    restart: always
    env_file:
      - ./weaviate.env
    volumes:
      - /mnt/md0/docker/weaviate:/var/lib/weaviate
      - /mnt/md0/backups/weaviate:/backups
        #  frontend:
        #    build:
        #      context: ./web
        #      dockerfile: Dockerfile.frontend
        #    command:
        #      - npm
        #      - run
        #      - dev
        #      - --port
        #      - '8005'
        #    tty: true
        #    image: frontend
        #    volumes: 
        #      - ./web:/app
        #    environment:
        #      - NODE_ENV=development
        #    deploy:
        #      restart_policy:
        #        condition: on-failure
        #        delay: 5s
        #        max_attempts: 5
        #    network_mode: host
        #  backend:
        #    build:
        #      context: ./
        #      dockerfile: Dockerfile.backend
        #    command:
        #      - uvicorn
        #      - api.main:app
        #      - --host
        #      - "0.0.0.0"
        #      - --port
        #      - "3000"
        #      - --reload
        #    tty: true
        #    image: backend
        #    volumes: 
        #      - ./src:/app/src
        #    env_file:
        #      ./.env
#   deploy:
#     restart_policy:
#       condition: on-failure
#       delay: 5s
#       max_attempts: 5
#    network_mode: host
#    


  
